name: laravel-apache-docker

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    command: >
      bash -c "php artisan migrate --force && php-fpm"
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - mysql-laravel-apache-docker:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-laravel-apache-docker:
